apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: maniar
      defaultBucket: gateway
      tlsSkipVerify: true
    secureJsonData:
      token: dev-token-do-not-use-in-prod
    editable: false
